Repository interviewr/raven-client, pull requests merged in 2018-08, with the labels that each got.

#29 Use cross-env package to run scripts on the Windows
  package.json
  yarn.lock
Labels: enhancement

#31 IB-30 Add Travis CI, build and push docker image
  .travis.yml
  Dockerfile
  Makefile
  nginx.conf
Labels: enhancement, feature

#33 Add missing build step on CI
  .travis.yml
  package.json
  webpack/base.js
  webpack/prod.js
  yarn.lock
Labels: bug

#35 IB-17: Create pure video component. Fix ui flashing
  src/components/LargeVideo/LargeVideo.jsx
  src/components/LargeVideo/index.js
  src/components/LargeVideo/theme.css
  src/components/RemoteVideosBox/RemoteVideosBox.jsx
  src/components/Video/Video.jsx
  src/components/Video/index.js
  src/components/Video/theme.css
  src/containers/Conference/Conference.jsx
  src/containers/Conference/theme.css
Labels: bug
