Repository interviewr/raven-client, pull requests merged in 2018-09, with the labels that each got.

#39 Setup test scripts
  .babelrc
  .eslintrc
  .gitignore
  jest.config.js
  package.json
  setupEnzyme.js
  src/components/ActionBar/ActionBar.jsx
  src/components/ActionBar/ActionBar.spec.jsx
  src/components/Button/Button.spec.jsx
  yarn.lock
Labels: enhancement

#41 Switch to standard instead of eslint, update babel
  .babelrc
  .eslintignore
  .eslintrc
  .travis.yml
  config/jest/setup.js
  config/webpack/base.js
  config/webpack/dev.js
  config/webpack/prod.js
  jest.config.js
  package.json
  postcss.config.js
  setupEnzyme.js
  src/actions/index.js
  src/components/ActionBar/ActionBar.jsx
  src/components/ActionBar/ActionBar.spec.jsx
  src/components/ActionBar/index.js
  src/components/Button/Button.jsx
  src/components/Button/Button.spec.jsx
  src/components/Button/index.js
  src/components/Icons/CallEnd.jsx
  src/components/Icons/Chat.jsx
  src/components/Icons/Code.jsx
  src/components/Icons/Mic.jsx
  src/components/Icons/MicOff.jsx
  src/components/Icons/Settings.jsx
  src/components/Icons/ShareScreen.jsx
  src/components/Icons/Video.jsx
  src/components/Icons/VideoOff.jsx
  src/components/Login/Login.jsx
  src/components/Login/index.js
  src/components/RemoteVideosBox/RemoteVideosBox.jsx
  src/components/RemoteVideosBox/index.js
  src/components/TextField/TextField.jsx
  src/components/TextField/index.js
  src/components/ToolBar/ToolBar.jsx
  src/components/ToolBar/index.js
  src/components/Video/Video.jsx
  src/components/Video/index.js
  src/constants/index.js
  src/containers/ActionBar.js
  src/containers/Conference/Conference.jsx
  src/containers/Conference/index.js
  src/containers/ToolBar.js
  src/index.jsx
  src/reducers/actionBar.js
  src/reducers/index.js
  src/reducers/peers.js
  src/reducers/toolbar.js
  src/sagas/conference.js
  src/sagas/index.js
  src/services/StreamStore.js
  src/services/history.js
  src/services/videoStream.js
  src/store/configureStore.js
  webpack.config.js
  yarn.lock
Labels: enhancement, question

#42 Speaker selection depending on volume level
  src/actions/index.js
  src/assets/fonts/OpenSans/OpenSans-Bold.ttf
  src/assets/fonts/OpenSans/OpenSans-BoldItalic.ttf
  src/assets/fonts/OpenSans/OpenSans-ExtraBold.ttf
  src/assets/fonts/OpenSans/OpenSans-ExtraBoldItalic.ttf
  src/assets/fonts/OpenSans/OpenSans-Italic.ttf
  src/assets/fonts/OpenSans/OpenSans-Light.ttf
  src/assets/fonts/OpenSans/OpenSans-LightItalic.ttf
  src/assets/fonts/OpenSans/OpenSans-Regular.ttf
  src/assets/fonts/OpenSans/OpenSans-SemiBold.ttf
  src/assets/fonts/OpenSans/OpenSans-SemiBoldItalic.ttf
  src/assets/images/intro.jpg
  src/components/ActionBar/ActionBar.jsx
  src/components/ToolBar/ToolBar.jsx
  src/components/ToolBar/index.js
  src/components/ToolBar/theme.css
  src/containers/ActionBar.js
  src/containers/Conference/Conference.jsx
  src/containers/Conference/index.js
  src/containers/ToolBar.js
  src/reducers/actionBar.js
  src/reducers/index.js
  src/reducers/peers.js
  src/reducers/toolbar.js
  src/sagas/index.js
  src/sagas/peer.js
  src/sagas/room.js
  src/services/Volumemeter.js
  src/services/localStream.js
  src/typography.css
Labels: DO NOT MERGE

#45 IB-19 Active screen selection using hark (depends on volume level)
  package.json
  src/actions/index.js
  src/components/RemoteVideosBox/RemoteVideosBox.jsx
  src/components/Video/Video.jsx
  src/containers/Conference/Conference.jsx
  src/containers/Conference/index.js
  src/reducers/peers.js
  src/sagas/activeSpeaker.js
  src/sagas/index.js
  src/services/Volumemeter.js
  yarn.lock
Labels: duplicate, enhancement, feature

#46 IB-43 Migrate to styled-components
  .babelrc
  config/webpack/dev.js
  config/webpack/prod.js
  package.json
  postcss.config.js
  src/common.css
  src/components/ActionBar/ActionBar.jsx
  src/components/ActionBar/ActionBar.spec.jsx
  src/components/ActionBar/theme.css
  src/components/Button/Button.jsx
  src/components/Button/theme.css
  src/components/Login/Login.jsx
  src/components/Login/theme.css
  src/components/RemoteVideosBox/RemoteVideosBox.jsx
  src/components/RemoteVideosBox/theme.css
  src/components/TextField/TextField.jsx
  src/components/TextField/theme.css
  src/components/Video/Video.jsx
  src/components/Video/theme.css
  src/constants/styles.js
  src/containers/Conference/Conference.jsx
  src/containers/Conference/index.js
  src/containers/Conference/theme.css
  src/globalStyles.js
  src/index.jsx
  src/sagas/room.js
  src/services/history.js
  src/store/configureStore.js
  src/typography.css
  src/variables.css
  yarn.lock
Labels: enhancement, investigation
